global:
  ingress:
    host: dmini.ru

apps:
  - name: account
    image:
      repository: depsemt2009
      tag: latest
    replicas: 1
    containerPort: 8300
    service:
      type: ClusterIP
      port: 8300
      targetPort: 8300
    rollouts:
      strategy: blueGreen
      autoPromotionEnabled: true

  - name: profile
    image:
      repository: depsemt2009
      tag: latest
    replicas: 1
    containerPort: 8300
    service:
      type: ClusterIP
      port: 8300
      targetPort: 8300
    rollouts:
      strategy: blueGreen
      autoPromotionEnabled: true
