apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minibank-ingress
  annotations:
    ingress.alb.yc.io/external-ipv4-address: 158.160.146.151
    kubernetes.io/ingress.class: "nginx"
    ingress.alb.yc.io/subnets: e9bcaajrdoservrkp4ec
    ingress.alb.yc.io/security-groups: enpf64v0tbjnqti9rfkt
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
spec:
  tls:
    - hosts:
        - bmini.ru
      secretName: k8s-secret
  rules:
  - host: bmini.ru
    http:
      paths:
      - path: /account
        pathType: Prefix
        backend:
          service:
            name: account-service
            port:
              number: 8300
      - path: /account/static
        pathType: Prefix
        backend:
          service:
            name: account-service
            port:
              number: 8300
      - path: /profile
        pathType: Prefix
        backend:
          service:
            name: profile-service
            port:
              number: 8300
      - path: /profile/static
        pathType: Prefix
        backend:
          service:
            name: profile-service
            port:
              number: 8300