{{- range .Values.apps }}
--
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-preview-service
spec:
  type: {{ .service.type }}
  ports:
  - port: {{ .service.port }}
    targetPort: {{ .containerPort }}
  selector:
    app: {{ .name }}
{{- end }}