{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .name }}-rollout
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image.repository }}/{{ .name }}:{{ $.Values.global.imageTag }}
          ports:
            - containerPort: {{ .containerPort }}
  strategy:
    blueGreen:
      activeService: {{ .name }}-service
      previewService: {{ .name }}-preview-service
      autoPromotionEnabled: true
{{- end }}
