{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.targetPort }}
  selector:
    app: {{ .name }}
---
{{- end }}

