apiVersion: v1
kind: Service
metadata:
  #name: "service-{{ .Values.app.name }}-{{ .Values.component }}-{{ .Values.global.deploymentColor }}"
  name: "account-service-{{ .Values.global.deploymentColor }}"
spec:
  type: TCP
  ports:
    - port: 8300
      targetPort: 8300
  selector:
    #app: "{{ .Values.app.name }}-{{ .Values.component }}-{{ .Values.global.deploymentColor }}"
    app: "{{ .Values.app.name }}-account"
    environment: "{{ .Values.global.deploymentColor }}"
---
apiVersion: v1
kind: Service
metadata:
  #name: "service-{{ .Values.app.name }}-{{ .Values.component }}-{{ .Values.global.deploymentColor }}"
  name: "profile-service-{{ .Values.global.deploymentColor }}"
spec:
  type: TCP
  ports:
    - port: 8300
      targetPort: 8300
  selector:
    #app: "{{ .Values.app.name }}-{{ .Values.component }}-{{ .Values.global.deploymentColor }}"
    app: "{{ .Values.app.name }}-profile"
    environment: "{{ .Values.global.deploymentColor }}"

