# Generated by Django 4.2.5 on 2023-10-31 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('full_names', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_profile_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('usernameid', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='account.users')),
            ],
        ),
    ]
