{{- if .Values.ingress.manage }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.app.name }}-ingress-{{ .Values.global.activeVersion }}"
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: "/account"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.app.name }}-account-service-{{ .Values.global.activeVersion }}"
                port:
                  number: {{ .Values.account.service.port }}
          - path: "/profile"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.app.name }}-profile-service-{{ .Values.global.activeVersion }}"
                port:
                  number: {{ .Values.profile.service.port }}
{{- end }}