apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.app.name }}-ingress-{{ .Values.environment }}"
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: "/account"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.account.app.name }}-{{ .Values.environment }}"
                port:
                  number: {{ .Values.account.app.port }}
          - path: "/profile"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.profile.app.name }}-{{ .Values.environment }}"
                port:
                  number: {{ .Values.profile.app.port }}