global:
  imagePullSecrets: []

app:
  name: "your-application"
  port: 8080

service:
  type: ClusterIP

ingress:
  enabled: true
  host: "example.com"

environment: "blue"

replicaCount: 1

account:
  app:
    port: 8082
  image:
    repository: "depsemt2009/account"
    tag: "latest" # Или конкретный тег, как в вашем примере
  service:
    port: 80

profile:
  app:
    port: 8081
  image:
    repository: "depsemt2009/profile"
    tag: "latest" # Или конкретный тег, как в вашем примере
  service:
    port: 80
