name: Django CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        ls /opt
        cd account
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
        pip install coverage
        pip install coveralls

    - name: Run tests with coverage
      run: |
        coverage run --source=app ./account/app/manage.py test
        coverage report

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.xml
        # Опционально, если вы хотите загрузить форматированный lcov report

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        files: coverage.json

