name: Continuous Integration
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup Test Directories
      run: |
        echo "SRC_DIR=account/app/" >> $GITHUB_ENV
        echo "TESTS_DIR=account/app/account/tests/tests_test.py" >> $GITHUB_ENV


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r account/requirements.txt
        pip install pytest pytest-cov pytest-django
        sudo apt-get update && sudo apt-get install tree

    - name: Display structure
      run: tree
    - name: Set DJANGO_SETTINGS_MODULE
      run: echo "DJANGO_SETTINGS_MODULE=account.app.app.settings" >> $GITHUB_ENV
    - name: Run tests with coverage
      run: |
        export PYTHONPATH="/home/runner/work/mini_work_k8s/mini_work_k8s:$PYTHONPATH"
        tree
        pytest ${{ env.TESTS_DIR }} --cov=${{ env.SRC_DIR }} --cov-report=xml

    - name: Generate unique filename for test results
      run: |
        echo "TEST_RESULTS_FILENAME=test-results-$(date +%s).xml" >> $GITHUB_ENV

    - name: Run tests and generate report
      run: |
        pwd
        pytest ${{ env.TESTS_DIR }} --junitxml=${{ env.TEST_RESULTS_FILENAME }}


    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: ${{ env.TEST_RESULTS_FILENAME }}
