name: Kubernetes Connection and Access Test

on:
  workflow_dispatch:

jobs:
  check-k8s-connection-and-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Check Kubernetes Cluster Connection
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin cluster-info

      - name: Get Nodes
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin get nodes

      - name: Get namespaces
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin get namespaces

      - name: Check Permissions to Create Pods
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin auth can-i create pods --namespace default

      - name: Create Ingress
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin auth can-i create pods --namespace default   
      
       #Ingress-контроллера NGINX
      - name: Create Ingress
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

      
          

      

