name: CI/CD with Blue-Green Deployment NEW

on:
  workflow_dispatch:

env:
  PROFILE_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/profile:${{ github.sha }}
  ACCOUNT_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/account:${{ github.sha }}
  FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}


jobs:

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #- name: Set up Helm
      #  uses: azure/setup-helm@v4
      #  with:
      #    version: v3.12.1

      - name: Install Helm
        uses: azure/setup-helm@v4.0.0
        with:
            version: v3.14.0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

  build-account:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./account
          file: ./account/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/account:${{ github.sha }}

  build-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./profile
          file: ./profile/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/profile:${{ github.sha }}

  deploy-in-k8s:
    runs-on: ubuntu-latest
    needs: [ build-profile, build-account, lint-test ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4.0.0
        with:
          version: v3.14.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Yandex Cloud CLI non-interactively
        run: |
            curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i $HOME/.yandex-cloud -n
            echo "$HOME/.yandex-cloud/bin" >> $GITHUB_PATH

      - name: Save Kubeconfig to File
        run: |
            echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yml
            chmod 600 kubeconfig.yml

      - name: Install Argo Rollouts CLI
        run: |
            curl -LO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64
            chmod +x ./kubectl-argo-rollouts-linux-amd64
            sudo mv ./kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts
            kubectl-argo-rollouts version
          


      - name: Deploy to Kubernetes
        run: |
            DATE=$(date +%Y%m%d-%H%M)
            COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            RELEASE_NAME=minibank-release-${DATE}-${COMMIT_SHA}
          
            # Обновление Helm чартов с новым образом
            helm upgrade --install minibank-release ./.k8s/charts/ --set global.imageTag=${{ github.sha }} --namespace default --kubeconfig=kubeconfig.yml
      
            kubectl-argo-rollouts get rollout account-rollout -n default --kubeconfig=kubeconfig.yml
            kubectl-argo-rollouts get rollout profile-rollout -n default --kubeconfig=kubeconfig.yml
          
          
            # Добавляем задержку для стабилизации подов
            echo "Waiting for pods to stabilize"
            sleep 60
          
            # Предполагается, что поды уже стабилизировались после развертывания
            # Выполнение миграций для пода приложения account
            echo "Applying migrations for the account application"
            ACCOUNT_POD=$(kubectl get pods -l app=account -n default -o jsonpath="{.items[0].metadata.name}")
            kubectl exec $ACCOUNT_POD -n default --kubeconfig=kubeconfig.yml -- python manage.py migrate
            
            # Выполнение миграций для пода приложения profile
            echo "Applying migrations for the profile application"
            PROFILE_POD=$(kubectl get pods -l app=profile -n default -o jsonpath="{.items[0].metadata.name}")
            kubectl exec $PROFILE_POD -n default --kubeconfig=kubeconfig.yml -- python manage.py migrate

      - name: Wait for Rollout to be ready (Account Service)
        run: |
          kubectl-argo-rollouts status account-rollout -n default --watch --timeout=600s --kubeconfig=kubeconfig.yml

      - name: Wait for Rollout to be ready (Profile Service)
        run: |
          kubectl-argo-rollouts status profile-rollout -n default --watch --timeout=600s --kubeconfig=kubeconfig.yml

      - name: Apply Django makemigrations, migrate and collectstatic (Account Service)
        run: |
          ACCOUNT_POD=$(kubectl get pod -l app=account -n default -o jsonpath="{.items[0].metadata.name}" --kubeconfig=kubeconfig.yml)
          kubectl exec $ACCOUNT_POD -n default --kubeconfig=kubeconfig.yml -- python manage.py makemigrations
          kubectl exec $ACCOUNT_POD -n default --kubeconfig=kubeconfig.yml -- python manage.py migrate
          kubectl exec $ACCOUNT_POD -n default --kubeconfig=kubeconfig.yml -- python manage.py collectstatic --noinput

      - name: Apply Django makemigrations, migrate and collectstatic (Profile Service)
        run: |
          PROFILE_POD=$(kubectl get pod -l app=profile -n default -o jsonpath="{.items[0].metadata.name}" --kubeconfig=kubeconfig.yml)
          kubectl exec $PROFILE_POD -n default --kubeconfig=kubeconfig.yml -- python manage.py makemigrations
          kubectl exec $PROFILE_POD -n default --kubeconfig=kubeconfig.yml -- python manage.py migrate
          kubectl exec $PROFILE_POD -n default --kubeconfig=kubeconfig.yml -- python manage.py collectstatic --noinput

      - name: Promote Rollout (Account Service)
        run: |
          kubectl-argo-rollouts promote account-rollout -n default --kubeconfig=kubeconfig.yml

      - name: Promote Rollout (Profile Service)
        run: |
          kubectl-argo-rollouts promote profile-rollout -n default --kubeconfig=kubeconfig.yml

      
     
      
      
      

