name: Kubernetes Connection and Access Test

on:
  workflow_dispatch:

jobs:
  check-k8s-connection-and-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Check Kubernetes Cluster Connection
        run: |
          export KUBECONFIG=${{ secrets.KUBECONFIG }}
          kubectl --kubeconfig=$KUBECONFIG cluster-info

      - name: Get Nodes
        run: |
          kubectl --kubeconfig=$KUBECONFIG get nodes

      - name: Get namespaces
        run: |
          kubectl --kubeconfig=$KUBECONFIG get namespaces

      - name: Check Permissions to Create Pods
        run: |
          kubectl create pods --namespace default --kubeconfig=$KUBECONFIG

      - name: Create Test Pod
        run: |
          
          kubectl --kubeconfig=$KUBECONFIG apply -f <<EOF
          apiVersion: v1
          kind: Pod
          metadata:
             name: test-pod
          spec:
             containers:
             - name: nginx
               image: nginx
          EOF

      - name: Wait for Pod to be Ready
        run: |
          kubectl wait --for=condition=ready pod/test-pod --timeout=60s --kubeconfig=$KUBECONFIG

      - name: Delete Test Pod
        run: |
          kubectl delete pod test-pod --kubeconfig=$KUBECONFIG
