name: Kubernetes Connection Test

on:
  workflow_dispatch:


jobs:
  check-k8s-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Check Kubernetes Cluster Connection
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin cluster-info

      - name: Get Nodes
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin get nodes

      - name: Get namespace
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin get namespace
      - name: Check Kubernetes Client and Server Versions
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin version