name: CI/CD с использованием Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Установка kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Настройка переменных среды для Kubeconfig и CA сертификата
        run: |
          echo "KUBECONFIG=${{ secrets.KUBECONFIG }}" >> $GITHUB_ENV
          echo "CA_PEM=${{ secrets.CA_PEM }}" >> $GITHUB_ENV

      - name: Проверка соединения с кластером Kubernetes
        run: |
          echo "$KUBECONFIG" | kubectl --kubeconfig=/dev/stdin cluster-info

      - name: Проверка узлов кластера
        run: |
          echo "$KUBECONFIG" | kubectl --kubeconfig=/dev/stdin get nodes


. (Root directory of your repository)
├── .github
│   └── workflows
│       └── ci-cd.yaml (Ваш скрипт GitHub Actions)
├── chart
│   ├── Chart.yaml (Описание чарта Helm для приложения account и profile)
│   ├── values.yaml (Стандартные значения для чарта account и profile)
│   └── templates
│       ├── deployment.yaml (Описание deployment для приложения account и profile)
│       ├── service.yaml (Описание service для приложения account и profile)
│       └── ingress.yaml (Описание Ingress для синей зеленой версии для для приложения account и profile)
│   
├── account
│   ├── Dockerfile (Dockerfile для сборки образа приложения account)
│   └── ... (Исходный код и ресурсы приложения account)
└── profile
    ├── Dockerfile (Dockerfile для сборки образа приложения profile)
    └── ... (Исходный код и ресурсы приложения profile)
