name: Kubernetes Connection Test

on:
  workflow_dispatch:

jobs:
  check-k8s-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
      

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ github.event.inputs.helm_version || 'latest' }}

      - name: Check Kubernetes Cluster Connection
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin cluster-info

      - name: Get Nodes
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin get nodes

      - name: Get namespaces
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin get namespaces

      - name: Check Helm Version
        run: |
          helm version

      - name: Create Pod
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin kubectl auth can-i create pods --namespace default
