name: Проверка кластера Kubernetes

on:
  workflow_dispatch:

jobs:
  check-k8s-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Применить тестовый Pod
        run: |
          echo 'apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: nginx
    image: nginx' | kubectl apply -f -
          
      - name: Подождать 30 секунд
        run: sleep 30

      - name: Проверить кластер Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" | kubectl --kubeconfig=/dev/stdin get nodes

      - name: Удалить тестовый Pod
        run: |
          kubectl delete pod test-pod
