name: Run test
on:
  push:
    branches-ignore:
      - main
  workflow_call:
  workflow_dispatch:
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app: account
            TESTS_DIR: "account/app/account/tests/tests_test.py"
          - app: profile
            TESTS_DIR: "profile/app/user_profile/tests/tests_test.py"
    permissions:
      checks: write
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ matrix.app }}/requirements.txt
        pip install pytest-cov pytest-django pytest-mock
        sudo apt-get update && sudo apt-get install tree

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: tree
      run: |
        tree

    - name: Run tests with coverage
      run: |
        pytest ${{ matrix.TESTS_DIR }} -vv --cov=api.calculator 
        #--cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.app }}


